# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_positive_elements <- function(Y, X, W) {
    .Call('_mcfda_rob_get_positive_elements', PACKAGE = 'mcfda.rob', Y, X, W)
}

get_psi <- function(tmp, n, k, method = "HUBER") {
    .Call('_mcfda_rob_get_psi', PACKAGE = 'mcfda.rob', tmp, n, k, method)
}

scale_M <- function(resid, s, method = "BISQUARE", maxit = 50L, tol = 0.0001) {
    .Call('_mcfda_rob_scale_M', PACKAGE = 'mcfda.rob', resid, s, method, maxit, tol)
}

IRLScpp <- function(Y, X, weight_ = NULL, method = "HUBER", maxit = 50L, tol = 0.0001, k = 1.345) {
    .Call('_mcfda_rob_IRLScpp', PACKAGE = 'mcfda.rob', Y, X, weight_, method, maxit, tol, k)
}

get_kernel_weight <- function(tmp, kernel = "epanechnikov") {
    .Call('_mcfda_rob_get_kernel_weight', PACKAGE = 'mcfda.rob', tmp, kernel)
}

locpolysmooth_cpp <- function(Lt, Ly, newt, method = "HUBER", kernel = "epanechnikov", bw = 0.1, k = 1.345, deg = 1L, maxit = 50L, tol = 0.0001) {
    .Call('_mcfda_rob_locpolysmooth_cpp', PACKAGE = 'mcfda.rob', Lt, Ly, newt, method, kernel, bw, k, deg, maxit, tol)
}

order_ <- function(x) {
    .Call('_mcfda_rob_order_', PACKAGE = 'mcfda.rob', x)
}

weighted_quantile_cpp <- function(dat, weights, p) {
    .Call('_mcfda_rob_weighted_quantile_cpp', PACKAGE = 'mcfda.rob', dat, weights, p)
}

weighted_quantile_top_cpp <- function(dat, weights, p) {
    .Call('_mcfda_rob_weighted_quantile_top_cpp', PACKAGE = 'mcfda.rob', dat, weights, p)
}

wrm_fit <- function(xdat, ydat, x0, weight_vec) {
    .Call('_mcfda_rob_wrm_fit', PACKAGE = 'mcfda.rob', xdat, ydat, x0, weight_vec)
}

get_kernel <- function(x_i, x, h, method) {
    .Call('_mcfda_rob_get_kernel', PACKAGE = 'mcfda.rob', x_i, x, h, method)
}

wrm_smooth_cpp <- function(x, y, h, xgrid, kernel) {
    .Call('_mcfda_rob_wrm_smooth_cpp', PACKAGE = 'mcfda.rob', x, y, h, xgrid, kernel)
}

smooth_spline_cpp <- function(x) {
    .Call('_mcfda_rob_smooth_spline_cpp', PACKAGE = 'mcfda.rob', x)
}

huber_cpp <- function(y, k = 1.5, tol = 1e-6) {
    .Call('_mcfda_rob_huber_cpp', PACKAGE = 'mcfda.rob', y, k, tol)
}

mean_Mest_cpp <- function(X, smooth = FALSE) {
    .Call('_mcfda_rob_mean_Mest_cpp', PACKAGE = 'mcfda.rob', X, smooth)
}

cov_Mest_cpp <- function(X, smooth = FALSE) {
    .Call('_mcfda_rob_cov_Mest_cpp', PACKAGE = 'mcfda.rob', X, smooth)
}

expand_grid_cpp <- function(x, y) {
    .Call('_mcfda_rob_expand_grid_cpp', PACKAGE = 'mcfda.rob', x, y)
}

local_M_1D <- function(x, t, new_t, h) {
    .Call('_mcfda_rob_local_M_1D', PACKAGE = 'mcfda.rob', x, t, new_t, h)
}

get_raw_cov_cpp <- function(X, mu, gr, diag = FALSE) {
    .Call('_mcfda_rob_get_raw_cov_cpp', PACKAGE = 'mcfda.rob', X, mu, gr, diag)
}

local_M_2D <- function(raw_cov, s, t, gr, h = 0.02) {
    .Call('_mcfda_rob_local_M_2D', PACKAGE = 'mcfda.rob', raw_cov, s, t, gr, h)
}

